@extends('layout.admin')
@section('content')
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
    ADMIN <br>
@endsection